name: Find Lowest Number 

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Test 1 10 numbers
      run: |
        python find_lowest_number.py test_data/test1_input.txt test1_output.txt
        diff test1_output.txt test_data/test1_expected.txt

    - name: Test 2 1 number
      run: |
        python find_lowest_number.py test_data/test2_input.txt test2_output.txt
        diff test2_output.txt test_data/test2_expected.txt

    - name: Test 3 blank file
      run: |
        python find_lowest_number.py test_data/test3_input.txt test3_output.txt
        diff test3_output.txt test_data/test3_expected.txt
